ALTER TABLE members ADD COLUMN banned INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN ban_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE members ADD COLUMN revision INTEGER NOT NULL DEFAULT 0;
