import {test} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import worker from '../server.mjs';
const profile={fullName:'Pessoa de Teste',cpf:'529.982.247-25',birthDate:'1995-05-20',gender:'not-informed',phone:'(99) 98115-0000',cep:'01001-000',state:'SP',city:'São Paulo',neighborhood:'Sé',street:'Praça da Sé',number:'10',complement:''};
test('Members: authentication, private orders, authoritative prices and verified reviews',async(t)=>{
// Reproduce the production Workers PBKDF2 ceiling rather than Node's unlimited implementation.
const nativeDeriveBits=crypto.subtle.deriveBits.bind(crypto.subtle);
t.mock.method(crypto.subtle,'deriveBits',async (algorithm,...args)=>{
 if(algorithm.name==='PBKDF2'&&algorithm.iterations>100000)throw new DOMException('Pbkdf2 failed: iteration counts above 100000 are not supported.','NotSupportedError');
 return nativeDeriveBits(algorithm,...args);
});
const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync(new URL('../drizzle/'+file,import.meta.url),'utf8'));
const env={ADMIN_EMAIL:'owner@example.test',DB:{prepare(sql){return{bind(...args){return{async first(){return db.prepare(sql).get(...args)||null}}}}}},ASSETS:{fetch:()=>new Response('ok')}};
async function call(path,body,cookie='',admin=false,origin='https://shop.test'){return worker.fetch(new Request('https://shop.test'+path,{method:body?'POST':'GET',headers:{'Origin':origin,'Content-Type':'application/json','X-SOS-Member':'1',Cookie:cookie,...(admin?{'oai-authenticated-user-id':'owner','oai-authenticated-user-email':env.ADMIN_EMAIL}:{})},...(body?{body:JSON.stringify(body)}:{})}),env)}
let result=await call('/api/members/register',{...profile,email:'test@example.test',password:'senha-de-teste-123'});assert.equal(result.status,200);const cookie=result.headers.get('set-cookie').split(';')[0];assert.match(result.headers.get('set-cookie'),/HttpOnly.*SameSite=Strict.*Secure/);
assert.equal((await call('/api/members/login',{email:'test@example.test',password:'senha-incorreta'})).status,401);
assert.equal((await call('/api/members/login',{email:'test@example.test',password:'senha-de-teste-123'})).status,200);
assert.notEqual(db.prepare('SELECT password_hash FROM members').get().password_hash,'senha-de-teste-123');
const storedPassword=db.prepare('SELECT password_hash,salt FROM members').get();
const legacyKey=await crypto.subtle.importKey('raw',new TextEncoder().encode('senha-de-teste-123'),'PBKDF2',false,['deriveBits']);
const legacyHash=Buffer.from(await nativeDeriveBits({name:'PBKDF2',salt:new TextEncoder().encode(storedPassword.salt),iterations:100000,hash:'SHA-256'},legacyKey,256)).toString('hex');
assert.equal(storedPassword.password_hash,'pbkdf2-sha256:100000:'+legacyHash,'Store explicit parameters for future compatibility');
assert.equal((await call('/api/members/orders')).status,401);
assert.equal((await call('/api/members/profile')).status,401);
const savedProfile=await(await call('/api/members/profile',undefined,cookie)).json();assert.equal(savedProfile.profile.cpf,'52998224725');assert.equal(savedProfile.profile.cep,'01001000');
assert.equal((await call('/api/members/profile',{...profile,cpf:'11111111111'},cookie)).status,403);
assert.equal((await call('/api/members/profile',{...profile,birthDate:'2023-02-31'},cookie)).status,403);
assert.equal((await call('/api/members/profile',{...profile,birthDate:'2999-01-01'},cookie)).status,403);
assert.equal((await call('/api/members/profile',{...profile,state:'XX'},cookie)).status,400);
assert.equal((await call('/api/members/profile',{...profile,phone:'123'},cookie)).status,400);
assert.equal((await call('/api/members/profile',{...profile,number:''},cookie)).status,400);
assert.equal((await call('/api/members/profile',profile,cookie,false,'https://evil.test')).status,403);
assert.equal((await(await call('/api/members/session',undefined,cookie)).json()).member.cpf,undefined);
for(const change of [{fullName:'Novo nome'},{name:'Novo nome'},{email:'novo@example.test'},{cpf:'11144477735'},{gender:'female'},{birthDate:'1990-01-01'}])assert.equal((await call('/api/members/profile',change,cookie)).status,403);
assert.equal((await call('/api/members/profile',{phone:'99999999999',street:'Rua editada'},cookie)).status,200);
const unchanged=await(await call('/api/members/profile',undefined,cookie)).json();assert.equal(unchanged.profile.fullName,profile.fullName);assert.equal(unchanged.profile.phone,'99999999999');assert.equal((await call('/api/members/profile',profile,cookie)).status,200);
let catalog=await(await call('/api/catalog')).json();catalog.settings.demo=false;db.prepare('INSERT INTO site_content(id,body,revision,updated_at) VALUES(?,?,1,?)').run('store',JSON.stringify(catalog),new Date().toISOString());
const purchase={requestKey:crypto.randomUUID(),items:[{id:'ssd',quantity:2,price:1}],total:1};
assert.equal((await call('/api/members/orders',purchase,cookie,false,'https://evil.test')).status,403);
result=await call('/api/members/orders',purchase,cookie);assert.equal(result.status,201);const {id}=await result.json();assert.equal((await(await call('/api/members/orders',purchase,cookie)).json()).id,id);
let account=await(await call('/api/members/orders',undefined,cookie)).json();assert.equal(account.orders.length,1);assert.equal(account.orders[0].customer.street,profile.street);await call('/api/members/profile',{...profile,street:'Outra rua'},cookie);const snapshot=await(await call('/api/members/orders',undefined,cookie)).json();assert.equal(snapshot.orders[0].customer.street,profile.street);assert.equal(account.orders[0].total,catalog.products.find(p=>p.id==='ssd').price*2);
const review={productId:'ssd',rating:4,text:'Gostei bastante do produto.'};assert.equal((await call('/api/members/reviews',review,cookie)).status,403);
assert.equal((await call('/api/admin/orders')).status,403);assert.equal((await call('/api/admin/orders/status',{id,status:'completed'},cookie)).status,403);
assert.equal((await call('/api/admin/orders/status',{id,status:'completed'},'',true)).status,200);
assert.equal((await call('/api/members/reviews',review,cookie)).status,201);assert.equal((await call('/api/members/reviews',review,cookie)).status,409);
assert.equal((await call('/api/members/reviews',{...review,productId:'ram'},cookie)).status,403);
assert.equal((await call('/api/members/profile',{...profile,fullName:'Pessoa Nome Atualizado'},cookie)).status,403);
const publicReviews=await(await call('/api/product-reviews?id=ssd')).json();assert.equal(publicReviews.reviews[0].verified,true);assert.equal(publicReviews.reviews[0].name,profile.fullName);assert.equal(publicReviews.reviews[0].email,undefined);for(const field of ['cpf','birthDate','gender','phone','customer','profile'])assert.equal(publicReviews.reviews[0][field],undefined);
const another=await call('/api/members/register',{...profile,fullName:'Outra Pessoa Teste',email:'other@example.test',password:'outra-senha-123'});const otherCookie=another.headers.get('set-cookie').split(';')[0];assert.equal((await(await call('/api/members/orders',undefined,otherCookie)).json()).orders.length,0);assert.equal((await call('/api/members/reviews',review,otherCookie)).status,403);
catalog.settings.demo=true;db.prepare('UPDATE site_content SET body=? WHERE id=?').run(JSON.stringify(catalog),'store');const demo=await(await call('/api/members/orders',{requestKey:crypto.randomUUID(),items:[{id:'ram',quantity:1}]},cookie)).json();assert.equal((await call('/api/members/reviews',{...review,productId:'ram'},cookie)).status,403);await call('/api/admin/orders/status',{id:demo.id,status:'completed'},'',true);assert.equal((await call('/api/members/reviews',{...review,productId:'ram'},cookie)).status,201);const demoReviews=await(await call('/api/product-reviews?id=ram')).json();assert.equal(demoReviews.reviews[0].demo,true);assert.equal(demoReviews.reviews[0].verified,false);

assert.equal((await call('/api/admin/users',undefined,cookie)).status,403);
const listed=await(await call('/api/admin/users',undefined,'',true)).json();assert.equal(listed.total,2);assert.equal(listed.users[0].password_hash,undefined);
const target=listed.users.find(u=>u.email==='test@example.test');
let detail=await(await call('/api/admin/users/detail?id='+target.id,undefined,'',true)).json();assert.equal(detail.reviews.length,2);assert.equal(detail.orders.length,2);assert.ok(detail.orders.every(o=>o.items.length>0));assert.equal(detail.orders.find(o=>o.id===id).total,account.orders[0].total);assert.equal((await call('/api/admin/users/detail?id='+target.id,undefined,otherCookie)).status,403);assert.equal(detail.user.password_hash,undefined);
assert.equal((await call('/api/admin/users/update',{id:target.id,revision:detail.user.revision,email:'updated@example.test',profile},cookie)).status,403);
assert.equal((await call('/api/admin/users/update',{id:target.id,revision:detail.user.revision,email:'other@example.test',profile},'',true)).status,409);
assert.equal((await call('/api/admin/users/update',{id:target.id,revision:detail.user.revision,email:target.email,profile:{...profile,city:'Cidade atualizada'}},'',true)).status,200);
assert.equal((await call('/api/admin/users/update',{id:target.id,revision:detail.user.revision,email:target.email,profile},'',true)).status,409);
detail=await(await call('/api/admin/users/detail?id='+target.id,undefined,'',true)).json();assert.equal(detail.user.profile.city,'Cidade atualizada');
assert.equal((await call('/api/admin/users/ban',{id:target.id,revision:detail.user.revision,banned:true,reason:'Teste'},'',true,'https://evil.test')).status,403);
assert.equal((await call('/api/admin/users/ban',{id:target.id,revision:detail.user.revision,banned:true,reason:'Teste'},'',true)).status,200);
assert.equal((await call('/api/members/orders',undefined,cookie)).status,401);
assert.equal((await call('/api/members/login',{email:target.email,password:'senha-de-teste-123'})).status,403);
assert.equal((await call('/api/members/profile',profile,cookie)).status,401);
assert.equal((await call('/api/members/reviews',review,cookie)).status,401);
detail=await(await call('/api/admin/users/detail?id='+target.id,undefined,'',true)).json();assert.equal(detail.user.banned,true);assert.equal(detail.reviews.length,2);
assert.equal((await call('/api/admin/users/ban',{id:target.id,revision:detail.user.revision,banned:false,reason:''},'',true)).status,200);
assert.equal((await call('/api/members/login',{email:target.email,password:'senha-de-teste-123'})).status,200);
await call('/api/members/logout',{},cookie);assert.equal((await call('/api/members/orders',undefined,cookie)).status,401);
db.close();
});
